mode: test
lmdb: False
dataset_root_rgb: './datasets'
lmdb_dir:  'I:\transform_2_lmdb'
dataset_json_folder: '/Youtu_Pangu_Security_Public/youtu-pangu-public/zhiyuanyan/DeepfakeBenchv2/preprocessing/dataset_json'

# label settings
label_dict:
  # DFD
  DFD_fake: 1
  DFD_real: 0
  # FF++ + FaceShifter(FF-real+FF-FH)
  FF-SH: 1
  FF-F2F: 1
  FF-DF: 1
  FF-FS: 1
  FF-NT: 1
  FF-FH: 1
  FF-real: 0
  # CelebDF
  CelebDFv1_real: 0
  CelebDFv1_fake: 1
  CelebDFv2_real: 0
  CelebDFv2_fake: 1
  # DFDCP
  DFDCP_Real: 0
  DFDCP_FakeA: 1
  DFDCP_FakeB: 1
  # DFDC
  DFDC_Fake: 1
  DFDC_Real: 0
  # DeeperForensics-1.0
  DF_fake: 1
  DF_real: 0
  # UADFV
  UADFV_Fake: 1
  UADFV_Real: 0
  # roop
  roop_Fake: 1
  roop_Real: 0

  # DF40 all
  FSAll_Fake: 1
  FSAll_Real: 0
  FRAll_Fake: 1 
  FRAll_Real: 0
  EFSAll_Fake: 1
  EFSAll_Real: 0


  # DF40
  e4s_Fake: 1
  e4s_Real: 0

  MidJourney_Fake: 1
  MidJourney_Real: 0

  deepfacelab_Fake: 1
  deepfacelab_Real: 0

  danet_Fake: 1
  danet_Real: 0

  fomm_Fake: 1
  fomm_Real: 0

  e4e_Fake: 1
  e4e_Real: 0

  hyperreenact_Fake: 1
  hyperreenact_Real: 0

  MRAA_Fake: 1
  MRAA_Real: 0

  one_shot_free_Fake: 1
  one_shot_free_Real: 0

  pirender_Fake: 1
  pirender_Real: 0

  tpsm_Fake: 1
  tpsm_Real: 0

  facedancer_Fake: 1
  facedancer_Real: 0

  facevid2vid_Fake: 1
  facevid2vid_Real: 0

  mcnet_Fake: 1
  mcnet_Real: 0

  fsgan_Fake: 1
  fsgan_Real: 0

  lia_Fake: 1
  lia_Real: 0

  mraa_Fake: 1
  mraa_Real: 0

  inswap_Fake: 1
  inswap_Real: 0

  simswap_Fake: 1
  simswap_Real: 0
  
  sadtalker_Fake: 1
  sadtalker_Real: 0

  wav2lip_Fake: 1
  wav2lip_Real: 0

  uniface_Fake: 1
  uniface_Real: 0

  blendface_Fake: 1
  blendface_Real: 0

  mobileswap_Fake: 1
  mobileswap_Real: 0

  faceswap_Fake: 1
  faceswap_Real: 0

  dalle2_face_Fake: 1
  dalle2_face_Real: 0

  MidJourney_Fake: 1
  MidJourney_Real: 0

  heygen_Fake: 1
  heygen_Real: 0

  whichisreal_Fake: 1
  whichisreal_Real: 0

  StyleGAN2_Fake: 1
  StyleGAN2_Real: 0

  StyleGAN3_Fake: 1
  StyleGAN3_Real: 0

  StyleGANXL_Fake: 1
  StyleGANXL_Real: 0

  ddim_Fake: 1
  ddim_Real: 0

  DiT_Fake: 1
  DiT_Real: 0

  pixart_Fake: 1
  pixart_Real: 0

  SiT_Fake: 1
  SiT_Real: 0

  sd1.5_Fake: 1
  sd1.5_Real: 0

  sd2.1_Fake: 1
  sd2.1_Real: 0

  VQGAN_Fake: 1
  VQGAN_Real: 0

  stargan_Fake: 1
  stargan_Real: 0

  starganv2_Fake: 1
  starganv2_Real: 0

  styleclip_Fake: 1
  styleclip_Real: 0

  CollabDiff_Fake: 1
  CollabDiff_Real: 0

  rddm_Fake: 1
  rddm_Real: 0

  # GenImage
  adm_Fake: 1
  adm_Real: 0

  pixart_Fake: 1
  pixart_Real: 0

  biggan_Fake: 1
  biggan_Real: 0

  glide_Fake: 1
  glide_Real: 0

  midjourney_Fake: 1
  midjourney_Real: 0

  sdv4_Fake: 1
  sdv4_Real: 0

  sdv5_Fake: 1
  sdv5_Real: 0

  vqdm_Fake: 1
  vqdm_Real: 0

  wukong_Fake: 1
  wukong_Real: 0
